"""
Report Generation Tool.
Generates HTML, CSV, and PDF executive reports using pure Python (fpdf2 for PDF).
"""

import io
from typing import Dict, Any, Optional
import pandas as pd
from fpdf import FPDF
from tools.data_profiler import profile_dataset


def generate_html_report(df: pd.DataFrame, meta: dict, executive_summary: str = "") -> str:
    """Generate a self-contained HTML executive report."""
    profile = profile_dataset(df)
    quality = profile.get("quality_info", {})
    
    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>AI Data Analyst Executive Report - {meta.get('filename', 'Dataset')}</title>
    <style>
        body {{ font-family: 'Inter', Helvetica, Arial, sans-serif; background: #0F172A; color: #F8FAFC; padding: 40px; margin: 0; }}
        .header {{ border-bottom: 2px solid #4F46E5; padding-bottom: 20px; margin-bottom: 30px; }}
        h1 {{ color: #818CF8; margin: 0 0 10px 0; font-size: 2rem; }}
        .subtitle {{ color: #94A3B8; font-size: 1rem; }}
        .section {{ background: #1E293B; border-radius: 12px; padding: 24px; margin-bottom: 25px; border: 1px solid rgba(255,255,255,0.08); }}
        h2 {{ color: #38BDF8; font-size: 1.3rem; margin-top: 0; border-bottom: 1px solid rgba(255,255,255,0.1); padding-bottom: 8px; }}
        .metric-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 20px; }}
        .metric-box {{ background: #0F172A; padding: 15px; border-radius: 8px; text-align: center; border: 1px solid rgba(255,255,255,0.05); }}
        .metric-label {{ font-size: 0.75rem; color: #94A3B8; text-transform: uppercase; }}
        .metric-val {{ font-size: 1.5rem; font-weight: bold; color: #F8FAFC; margin-top: 5px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
        th, td {{ padding: 10px 14px; text-align: left; border-bottom: 1px solid rgba(255,255,255,0.05); }}
        th {{ background: #0F172A; color: #818CF8; font-size: 0.85rem; }}
        td {{ font-size: 0.85rem; color: #CBD5E1; }}
        .footer {{ text-align: center; font-size: 0.8rem; color: #64748B; margin-top: 40px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>AI Data Analyst Executive Report</h1>
        <div class="subtitle">Dataset: <strong>{meta.get('filename', 'Dataset')}</strong> | Generated automatically</div>
    </div>

    <div class="section">
        <h2>📌 Executive Summary</h2>
        <p>{executive_summary or 'This executive report summarizes data health, profiling metrics, and key statistical insights.'}</p>
    </div>

    <div class="section">
        <h2>📊 Dataset Profile & Quality Score</h2>
        <div class="metric-grid">
            <div class="metric-box"><div class="metric-label">Total Rows</div><div class="metric-val">{profile.get('total_rows', 0):,}</div></div>
            <div class="metric-box"><div class="metric-label">Total Columns</div><div class="metric-val">{profile.get('total_cols', 0)}</div></div>
            <div class="metric-box"><div class="metric-label">Missing Cells</div><div class="metric-val">{profile.get('missing_pct', 0)}%</div></div>
            <div class="metric-box"><div class="metric-label">Quality Score</div><div class="metric-val">{quality.get('score', 0)}/100</div></div>
        </div>
        <p><strong>Quality Assessment:</strong> {quality.get('label', 'N/A')}</p>
    </div>

    <div class="section">
        <h2>📑 Data Sample Preview (First 10 Rows)</h2>
        {df.head(10).to_html(classes="table", index=False)}
    </div>

    <div class="footer">
        Generated by AI Data Analyst Agent • Confidential
    </div>
</body>
</html>"""
    return html


def generate_pdf_report(df: pd.DataFrame, meta: dict, executive_summary: str = "") -> bytes:
    """Generate PDF executive report using pure-Python fpdf2."""
    profile = profile_dataset(df)
    quality = profile.get("quality_info", {})

    pdf = FPDF()
    pdf.add_page()

    # Colors
    pdf.set_fill_color(15, 23, 42)
    pdf.rect(0, 0, 210, 297, "F")  # Dark background

    # Title
    pdf.set_text_color(129, 140, 248)
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 15, "AI Data Analyst Executive Report", ln=True, align="L")

    pdf.set_text_color(148, 163, 184)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Dataset: {meta.get('filename', 'Uploaded Dataset')}", ln=True, align="L")
    pdf.ln(5)

    # Executive Summary Box
    pdf.set_fill_color(30, 41, 59)
    pdf.set_draw_color(79, 70, 229)
    pdf.rect(10, 40, 190, 35, "FD")

    pdf.set_xy(15, 43)
    pdf.set_text_color(56, 189, 248)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Executive Summary", ln=True)

    pdf.set_xy(15, 52)
    pdf.set_text_color(248, 250, 252)
    pdf.set_font("Helvetica", "", 10)
    summary_text = executive_summary[:250] if executive_summary else "Automated data analysis and data health summary report."
    pdf.multi_cell(180, 5, summary_text)

    # Metrics Section
    pdf.set_xy(10, 85)
    pdf.set_text_color(129, 140, 248)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Dataset Key Metrics", ln=True)

    metrics = [
        ("Total Rows", f"{profile.get('total_rows', 0):,}"),
        ("Total Columns", f"{profile.get('total_cols', 0)}"),
        ("Missing Cells %", f"{profile.get('missing_pct', 0)}%"),
        ("Data Quality Score", f"{quality.get('score', 0)}/100 ({quality.get('label')})"),
    ]

    pdf.set_font("Helvetica", "", 10)
    for label, val in metrics:
        pdf.set_text_color(148, 163, 184)
        pdf.cell(60, 8, f"{label}:", align="L")
        pdf.set_text_color(248, 250, 252)
        pdf.cell(130, 8, val, ln=True, align="L")

    return bytes(pdf.output())
